### Get all contacts
GET http://localhost:3000/contacts

### Get contact by ID (replace with a real _id from your DB)
GET http://localhost:3000/contacts/68260227e7da943c2d460996

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Matilda",
  "lastName": "Amoni",
  "email": "matilda@example.com",
  "favoriteColor": "Red",
  "birthday": "1997-01-05"
}

### Update a contact (replace ID)
PUT http://localhost:3000/contacts/682eec6d59c7df2c9995e652
Content-Type: application/json

{
  "firstName": "Matilda",
  "lastName": "Amoni",
  "email": "matilda@example.com",
  "favoriteColor": "Red",
  "birthday": "1997-01-05"
}

### Delete a contact (replace ID)
DELETE http://localhost:3000/contacts/682eec6d59c7df2c9995e652
